In [1]:
### importing important libraries.
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## Sentence.
sent=['The glass of milk',
      'the glass of juice',
      'the cup of tea',
      'i am good boy',
      'I am good developer',
      'understand the meaning of word',
      'your videos are good']

In [3]:
sent

['The glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am good boy',
 'I am good developer',
 'understand the meaning of word',
 'your videos are good']

In [4]:
### Initializing the vocab size.
voc_size=10000

### One hot Representation

In [8]:
onehot_rep=[one_hot(words,voc_size)for words in sent]
print(onehot_rep)

[[5240, 462, 3090, 2685], [5240, 462, 3090, 8543], [5240, 7201, 3090, 3989], [4153, 5106, 8370, 3449], [4153, 5106, 8370, 8215], [5252, 5240, 4381, 3090, 2009], [1587, 1259, 4392, 8370]]


### Word Embedding Presentation.

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [14]:
import numpy as np
sent_length=8
embedded_doc=pad_sequences(onehot_rep,padding='pre',maxlen=sent_length)
print(embedded_doc)

[[   0    0    0    0 5240  462 3090 2685]
 [   0    0    0    0 5240  462 3090 8543]
 [   0    0    0    0 5240 7201 3090 3989]
 [   0    0    0    0 4153 5106 8370 3449]
 [   0    0    0    0 4153 5106 8370 8215]
 [   0    0    0 5252 5240 4381 3090 2009]
 [   0    0    0    0 1587 1259 4392 8370]]


In [15]:
### proving the dimention.
dim=10

In [16]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [18]:
### printing  values in sparx matrix.
print(model.predict(embedded_doc))

[[[ 0.02660474 -0.04969214 -0.0183592   0.01891157 -0.00630601
    0.02705426 -0.03234012 -0.00335344  0.03554412  0.00321098]
  [ 0.02660474 -0.04969214 -0.0183592   0.01891157 -0.00630601
    0.02705426 -0.03234012 -0.00335344  0.03554412  0.00321098]
  [ 0.02660474 -0.04969214 -0.0183592   0.01891157 -0.00630601
    0.02705426 -0.03234012 -0.00335344  0.03554412  0.00321098]
  [ 0.02660474 -0.04969214 -0.0183592   0.01891157 -0.00630601
    0.02705426 -0.03234012 -0.00335344  0.03554412  0.00321098]
  [ 0.02754783  0.00145278 -0.04020865  0.00514514  0.04785507
    0.00432588  0.02641692  0.01356356 -0.02006632 -0.03840427]
  [ 0.01489762  0.04321029 -0.04578335  0.01170052  0.00841495
   -0.01862014 -0.04320721 -0.04886637 -0.01233183  0.0357211 ]
  [ 0.01622755 -0.02352743 -0.04434793  0.02455069  0.02913422
   -0.03380045 -0.04943959  0.00831081 -0.01953292  0.03335804]
  [ 0.03571154 -0.02673072  0.04557038  0.00124343  0.01745896
    0.04229832 -0.03698276 -0.0092929  -0.044777

In [19]:
embedded_doc[0]

array([   0,    0,    0,    0, 5240,  462, 3090, 2685])